### ISSUE TITLE
Wrong page for downloading

### ISSUE THREAD

**Issue by IKnewOne** [NetroScript/Graveyard-Keeper-Savefile-Editor#1]
Update message has https://github.com/NetroScript/raveyard-Keeper-Savefile-Editor link, which is wrong

**Comment by NetroScript** [comment]
This was already fixed inhttps://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/commit/531abdbd6c8dce96fa5563cf4dfe506688a10b08 but currently I am waiting with the release 0.1.1 because I am looking into a bug of the game, where I maybe can add a fix in the save file editor
