### ISSUE TITLE
save file was broken

### ISSUE THREAD

**Issue by SeRRedz** [NetroScript/Graveyard-Keeper-Savefile-Editor#15]
Good day, I have a problem, my save file was broken by this bug, could you add a byte to the right place in my save?

**Comment by NetroScript** [comment]
Upload the save file here to GitHub, I will take a look at it after my lunch and if that byte is missing, I will add it and then upload the repaired save file back here.

**Comment by SeRRedz** [comment]
[Graveyard Keeper.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2339650/Graveyard.Keeper.zip)

**Comment by NetroScript** [comment]
[1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2339773/1.zip)
Just replace your 1.dat file with that and it should be fixed, (I tested it, my game is loading it without problems)

**Comment by SeRRedz** [comment]
Thank you so much
