### ISSUE TITLE
The save file was broken after adding smth to the inventory 

### ISSUE THREAD

**Issue by MisterEpicMann** [NetroScript/Graveyard-Keeper-Savefile-Editor#17]

**Comment by MisterEpicMann** [comment]
After I tried to add 3 carved pieces of marble of the golden quality, and then launched the game. The game file appeared to be broken and doesnt start

**Comment by MisterEpicMann** [comment]
Now it works properly, but why has it bugged?

**Comment by NetroScript** [comment]
What works properly now?

**Comment by MisterEpicMann** [comment]
Doesnt 3 pieces of carved marble doesnt exist?

**Comment by NetroScript** [comment]
It does exist, it works fine for my save

**Comment by MisterEpicMann** [comment]
The save works well now
Thnx :)

**Comment by NetroScript** [comment]
So now you can edit it again without a problem and save and load it?

**Comment by NetroScript** [comment]
If that is the case maybe the write process was interrupted

**Comment by MisterEpicMann** [comment]
Yes I can play it and edit it

**Comment by MisterEpicMann** [comment]
But I actually tried to add 3 pieces again and the save was corrupted once more

**Comment by NetroScript** [comment]
Did you update the editor?
To 0.1.5

**Comment by MisterEpicMann** [comment]
Not yet

**Comment by MisterEpicMann** [comment]
Should I?

**Comment by NetroScript** [comment]
That's the problem

**Comment by NetroScript** [comment]
In 0.1.3 a bug was introduced which breaks the save files because when packing strings in 1 specific case (for the string "@snake_1D") a byte was missing when saving again, making it unreadable, because the length of a word is stored, then that word is read, but this was offset by 1 meaning a word was interpreted as a length of a word leading to errors.

**Comment by MisterEpicMann** [comment]
I see then, should I get the latest version?

**Comment by NetroScript** [comment]
Yes

**Comment by NetroScript** [comment]
Just use the backup you have (the .back file) and edit it with the new version and the error shouldn't occur again.

**Comment by MisterEpicMann** [comment]
Everything works properly. Thnx a lot m8 👍
