### ISSUE TITLE
Hunter's medallion has missing texture

### ISSUE THREAD

**Issue by IKnewOne** [NetroScript/Graveyard-Keeper-Savefile-Editor#20]
Just leaving it here because there's no such item in wiki, and i don't know how to extract it
internal name is 'hunters_medallion"

**Comment by NetroScript** [comment]
Will take a look at it, when I have time

**Comment by NetroScript** [comment]
Was closed by https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/commit/e59eccb47ebd267d0c7b6ea5d7b6cc8463e69ff3
