### ISSUE TITLE
Getting the program running

### ISSUE THREAD

**Issue by Kobra299** [NetroScript/Graveyard-Keeper-Savefile-Editor#29]
I just downloaded the newest version of you program and tried to run it but it failed because of some thing or other I was wondering where the program is ment to go eg in the graveyard keeper folder or one for just the program

**Comment by Zaf9670** [comment]
It should just work no matter where it's installed. He also gives instructions on how to pull up whatever errors may be occurring.

I am also having issues though and it appears to be trying to load Python from a J:\ directory and then proceeds to a "FileNoteFoundError"

**Comment by Zaf9670** [comment]
And I think I already found the error of my ways. It let me continue forward without actually setting a path. I assumed the pre-populated text was already going to the directory...

**Comment by NetroScript** [comment]
Delete the settings file and restart th program to select the path again. And the "J:\" is no problem, the precompiled version is my installation frozen --> you see errors on my original paths (like 'J:\Programme\Python64' instead of the path where you have it)

**Comment by Kobra299** [comment]
that was part of the issue other part was not having eel installed

**Comment by NetroScript** [comment]
Although installing eel is in the installation instructions for manual installation

**Comment by Kobra299** [comment]
yea but I missed reading that part
