### ISSUE TITLE
Modify Reputation?

### ISSUE THREAD

**Issue by rcreasey** [NetroScript/Graveyard-Keeper-Savefile-Editor#3]
Is there any way to modify the reputation with npcs in the save file?

I have a bugged save with rep for the merchant that will make me have to reset. 😞

**Comment by NetroScript** [comment]
The app currently can't do it - but it can export JSON so you could manually edit the JSON data. I don't know if a task / quest is bugged or the value for the reputation - if you want to edit the tasks / quests you can modify the JSON file in savedata - known_npcs - v - npcs --> There you have an array with all the npc's, find the one with the correct npc_id and then go to tasks -> find the most recent task and set the state to complete. But the game also stores your current reputation in the inventory --> to modify that in the JSON go to savedata - _inventory - _params - v - _res_type --> which is an array again, which contains names of attributes - search for the one which is called "_rel_<the id of your npc>" - remember its position in the list and then change the value of the same position in _res_v

**Comment by rcreasey** [comment]
Holy hell... This is an ~90Mb json file. 

I'll take a look at the questline and see if I can fix this.

Thanks again and awesome work!
