### ISSUE TITLE
Windows - Black screen, no error

### ISSUE THREAD

**Issue by SammieLouise** [NetroScript/Graveyard-Keeper-Savefile-Editor#31]
Hi, I'm not sure how helpful I can be. I tried to use 0.1.6 Windows release; running the .exe opens a black console window which remained opened, but displayed no error message or text of any kind. If there's something I can do to give you actual information, please let me know?

**Comment by SammieLouise** [comment]
I had thought I'd left it for several minutes, but upon your question I tried it again and it launched properly after a few minutes! My apologies; and thanks for this tool!

**Comment by NetroScript** [comment]
Yeh the compiled version needs some time to start itself because it is packed and it has to load all the packe data, I am playing with the thought to leave it unpacked where you will have far more files then but also faster start up time.
