### ISSUE TITLE
Deleting items on the ground

### ISSUE THREAD

**Issue by kingappa** [NetroScript/Graveyard-Keeper-Savefile-Editor#34]
There are 3000 wooden planks on the ground in my church and the game doesn't launch because of it how can I use the save editor to delete them?

**Comment by NetroScript** [comment]
Just start the application, select/open the save file which doesn't load. And in the first section (Generic) there is a button "Remove all drops". (Below the input for your energy)

**Comment by kingappa** [comment]
thanks)

**Comment by NetroScript** [comment]
So all problems fixed? Then I will close the issue.

**Comment by kingappa** [comment]
Yeah, go ahead thanks again)
