### ISSUE TITLE
[BUG] Item insert is bugged for me #2

### ISSUE THREAD

**Issue by lordfiSh** [NetroScript/Graveyard-Keeper-Savefile-Editor#40]
**Describe the bug**
inserted Pen & Ink and Flyers, now I have 3 Inventories. Everything still seems to work, but I don't think it should be this way ;) 

**To Reproduce**
[Graveyard Keeper.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2718578/Graveyard.Keeper.zip)

**Expected behavior**
to have only one

**Screenshots**
![image](https://user-images.githubusercontent.com/389680/50563653-f5786980-0d1e-11e9-8d6b-1d9002ca3cb9.png)

**Please also add the following Information:**
* Used version of the save game editor
up2date

ps: thanks for this tool. I couldn't load my alpha-save and now I can skip to the zombie part ;)

**Comment by NetroScript** [comment]
Closed by https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/commit/3540c312b23ad498ed4b7c79475415f502c05b31

This should be the first chance to test the new self update system.
Although I have to say when I tried it the browser (GUI window) did not automatically close, so don't forget that if it stays open to close it manually.

**Comment by lordfiSh** [comment]
GUI Update works, but the windows dosen't close automaticly

> Finished updating - now closing
Traceback (most recent call last):
  File "J:\Programme\Python64\lib\site-packages\gevent\greenlet.py", line 536, in run
  File "J:\Programme\Python64\lib\site-packages\eel\__init__.py", line 191, in _process_message
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 100, in updateitemversion
NameError: name 'exit' is not defined
Mon Dec 31 17:43:11 2018 <Greenlet at 0x23c0e60f6d0: _process_message({'call': 3.6232955280631987, 'name': 'updateitemve, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with NameError

**Comment by NetroScript** [comment]
But I am reluctant to do a 0.1.10 version for a code change of 1 line, I will commit it but the version will only be changed when I do some other code changes so it would be worth it. In future item changes (before the version 0.1.10 is out) I can also add the text "Please manually close the GUI when the console is back to input mode"
