### ISSUE TITLE
bitmap "./data/html/favicon.ico" not defined

### ISSUE THREAD

**Issue by Karlodun** [NetroScript/Graveyard-Keeper-Savefile-Editor#43]
Traceback (most recent call last):
  File "main.py", line 674, in <module>
    root.iconbitmap("./data/html/favicon.ico")
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 1868, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "./data/html/favicon.ico" not defined

running under OpenSUSE.
I overcome the issue by commenting this line out, then it works. File is there, path seems ok. Can't find a better solution. However since we are hiding tk anyways, do we actually need this file?

There is a stackoverflow topic on this issue:
from https://stackoverflow.com/questions/11176638/tkinter-tclerror-error-reading-bitmap-file
First, you'll need to create an icon and save it in two formats: Windows "ico" and Unix "xbm". 64 x 64 is a good size. XBM is a 1-bit format--pixels just on or off, so no colors, no grays. Linux implementations of tkinter only accept XBM even though every Linux desktop supports real icons, so you're just out of luck there. Also, the XBM spec is ambiguous about whether "on" bits represent black or white, so you may have to invert the XBM for some desktops. Gimp is good for creating these.

**Comment by NetroScript** [comment]
I can only imagine that the .ico format is not compatible with the Tkinter implementation on OpenSUSE.

Can you try putting the attached .png file in the same folder and replacing 
```python
root.iconbitmap("./data/html/favicon.ico")
```

with 

```python
root.iconphoto(True, PhotoImage(file="./data/html/favicon.png"))
```
Maybe it will be work them, other than that I can only imagine tkinter having a problem with the relative path. 
If the upper one doesn't work you could try:

```python
root.iconbitmap(os.path.join(sys.path[0], "/data/html/favicon.ico"))
```

[favicon.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2730012/favicon.zip)

**Comment by NetroScript** [comment]
Add to the top:
`from tkinter import PhotoImage`

**Comment by Karlodun** [comment]
just did it 2 mins ago... :-)

**Comment by Karlodun** [comment]
is working, maybe it would be a good solution for both, lin+win?

**Comment by Karlodun** [comment]
btw, right click seems not to work there, nor the menues. I would like to improve the design, but need to enable debugger. Any ideas?

**Comment by Karlodun** [comment]
done, hotkey works. thanks! hope this issue can be fixed.
And I'll try and provide some improvement to the css and html.

**Comment by NetroScript** [comment]
Sorry for the late answer, every html page has this close to the beginning 
```JavaScript
        // There is no intended right click behaviour, so let's disable it
        $(document).contextmenu(function (e) {
            e.preventDefault()
        })
```
Just remove that. And using PhotoImage is working or the 3rd variant?

**Comment by changj1** [comment]
Wow, It's work. I got a right solution. Thank you.

**Comment by AgustinStringa** [comment]
> I can only imagine that the .ico format is not compatible with the Tkinter implementation on OpenSUSE.
> 
> Can you try putting the attached .png file in the same folder and replacing
> 
> ```python
> root.iconbitmap("./data/html/favicon.ico")
> ```
> 
> with
> 
> ```python
> root.iconphoto(True, PhotoImage(file="./data/html/favicon.png"))
> ```
> 
> Maybe it will be work them, other than that I can only imagine tkinter having a problem with the relative path. If the upper one doesn't work you could try:
> 
> ```python
> root.iconbitmap(os.path.join(sys.path[0], "/data/html/favicon.ico"))
> ```
> 
> Ah and add `import sys` to the top if you should try the last one.
> 
> [favicon.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2730012/favicon.zip)

gracias pibe, la verdad estaba renegando mucho y esta solucion me fue muy útil

**Comment by tute123456** [comment]
esto ultimo root.iconbitmap(os.path.join(sys.path[0], "/data/html/favicon.ico")) con import sys me funciono! gracias!
