### ISSUE TITLE
Cannot execute main.py

### ISSUE THREAD

**Issue by michaeldai7** [NetroScript/Graveyard-Keeper-Savefile-Editor#45]

**Comment by michaeldai7** [comment]
![grave](https://user-images.githubusercontent.com/43862422/51607798-8da2e200-1eca-11e9-911d-cb21812531d0.png)

**Comment by NetroScript** [comment]
Looks like you are using Ubuntu, I think running `sudo apt-get install python3.6-tk` should fix it. (I assumed tkinter is included by default in all python packages)

**Comment by NetroScript** [comment]
What does it say now that you have tkinter + install eel again?

**Comment by michaeldai7** [comment]
![eel](https://user-images.githubusercontent.com/43862422/51856078-99840f00-22e3-11e9-9b69-cb17d8a23b0c.png)

**Comment by michaeldai7** [comment]
it seems it didn't installed correctly

**Comment by NetroScript** [comment]
If you write `pip install eel` it uses most likely the pip module from python 2.x, so to install the module for the python version you are using, you should use `python3.6 -m pip install eel`

**Comment by NetroScript** [comment]
So is there still an issue or can this be closed. (If there is no response within the next 2 weeks I will take this as being inactive and close it)

**Comment by michaeldai7** [comment]
![image](https://user-images.githubusercontent.com/43862422/53353936-a2640280-38da-11e9-8153-4b2f28d253a6.png)

**Comment by NetroScript** [comment]
Seems like that Python installation is without the `pip` module, you can install it using 

```
wget https://bootstrap.pypa.io/get-pip.py
sudo python3.6 get-pip.py
```
or 
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python3.6 get-pip.py
```

**Comment by michaeldai7** [comment]
Thanks, it works
