### ISSUE TITLE
Cannot execute main.py on OSX 10.14.2

### ISSUE THREAD

**Issue by Plextron** [NetroScript/Graveyard-Keeper-Savefile-Editor#46]
When i try to start main.py on OSX 10.14.2 i got this message.

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from data.types import id_to_name, gamedata, Types, fallback_item
ImportError: No module named data.types

**Comment by Plextron** [comment]
**Fix:** Just start with 

**$ python3 main.py**

**Comment by NetroScript** [comment]
Problem solved so the issue can be closed?
Also I added to the installation section that if `python` is by default python 2.x on your system you need to use `python3`

**Comment by Plextron** [comment]
Thanks. Btw. Good work! 


-Closed-
