### ISSUE TITLE
[BUG] Perfect Bodies / Workers bugged

### ISSUE THREAD

**Issue by Iskieria** [NetroScript/Graveyard-Keeper-Savefile-Editor#49]
**Describe the bug**
The 'perfect body' functionality instead REDUCES bodies to 2 white skulls.
The perfect worker reduces them to 5%
No graveyard fences/headstones are added

**To Reproduce**
1. Go to 'Generic' section of the Save Editor.
2. Click on 'Set all workers ...' / "Replace all bodies in graves ..." 
3. Scroll down to 'Save to Saveslot'
4. Run Game; notice error

**Expected behavior**
Worker efficiency at 40%, and perfect bodies in graveyard. 

**Screenshots**
Set worker efficiency to 40% causes this:
![image](https://user-images.githubusercontent.com/11174174/52966055-38a99d00-339e-11e9-8544-814c0ff520d6.png)

Make existing bodies perfect results in this:
![image](https://user-images.githubusercontent.com/11174174/52965950-f7b18880-339d-11e9-831b-731649fab73d.png)

Fill empty graves results in this:
![image](https://user-images.githubusercontent.com/11174174/52965906-d486d900-339d-11e9-8944-d1893ee8f34a.png)

**Please also add the following Information:**
Newest release 0.1.12
Windows version

**Comment by NetroScript** [comment]
So I took a look at it and found out the problem, the editor works as intended, but when the game loads the save file, it resets the body (more or less) to a body you could have made with your current tech tree. Meaning before you can use this, you have to unlock all the necessary technologies (to be more specific the embalming ones) - this is demonstrated in this [video](https://streamable.com/30007) - I will add a note to the editor.

**Comment by Iskieria** [comment]
Ah okay, was a bit annoying since it reduced all my bodies, lol, but I'll give unlocking a go :)
