### ISSUE TITLE
Program not finding Save Files

### ISSUE THREAD

**Issue by Saadian** [NetroScript/Graveyard-Keeper-Savefile-Editor#50]
Error is in first screenshot. I definitely have a save file, as shown in my second screenshot. 
![image](https://user-images.githubusercontent.com/16518981/58489373-11175d00-8163-11e9-8fd5-78a9fb2a5b1a.png)

![image](https://user-images.githubusercontent.com/16518981/58489487-458b1900-8163-11e9-8c2d-bf5afc28bdd1.png)

**Comment by NetroScript** [comment]
It finds your save file, but fails when extracting the information from the save (to be exact when it tries to read your current church rating) - can you upload your 1.info here so I can see what exactly is causing the error?

**Comment by Saadian** [comment]
I can't upload the 1.info directly, according to GitHub. Hopefully this works?
[New Compressed (zipped) Folder.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/3229323/New.Compressed.zipped.Folder.zip)

**Comment by Saadian** [comment]
Apparently my game didn't actually save, as I'd started again. I'll restart, and make sure I definitely get a save. This might solve the issue for me.

**Comment by Saadian** [comment]
It's working now. Looks like the issue was caused by the game not saving. Thanks for the help!
