### ISSUE TITLE
[BUG] Current version of the app refuses to save a .dat file, no errors, no logs

### ISSUE THREAD

**Issue by maddzi** [NetroScript/Graveyard-Keeper-Savefile-Editor#54]
**Describe the bug**
Current version of the app refuses to save a .dat file, no errors, no logs, as if the button "export" doesn't exist there at all

**Comment by NetroScript** [comment]
Can you give me your save file where it is not working? And with the DLC or with the 1.200 Version?
I took a quick look at the code changes of 1.200 when it came out, but didn't see anything which would cause the save editor to fail.

**Comment by NetroScript** [comment]
I just tested also an older save I had from a reddit user (which I loaded, and then saved in the new version) and I was able to load that save and save it again without any problems

**Comment by maddzi** [comment]
Sorry, false alarm, I figured it out myself already, there was no problem in your code, but in Opera data processing peculiarities. I have the DLC version of the game, and everything works fine now. Your piece was used to divert some accidental mistakes I made in .dat file which caused the engine to crash when trying to load my savegame, and for that you have my utmost gratitude :)

**Comment by NetroScript** [comment]
Closing as it was resolved
