### ISSUE TITLE
[Suggestion] "Reset Dungeon" button

### ISSUE THREAD

**Issue by nonchip** [NetroScript/Graveyard-Keeper-Savefile-Editor#70]
should be as easy as clearing the (in the json representation) `savedata.dungeons._saved_dungeons` array and (via a checkbox or 2nd "reset and randomize" button) optionally rerolling the `savedata.dungeons._global_seed` integer (assuming that's actually random per-savegame) to generate a new one for more replayability.

there might be another stat somewhere that tracks which levels are unlocked, not sure, but in that case that obviously would need to be found&reset too, but as far as i can see it looks like it only cares about the maps generated in `_saved_dungeons` (and "unlocking" one seems to be done just by it being generated&saved when first entering it).

---
for reference, on a savegame where i never visited the dungeon, the `savedata.dungeons` object looks like this:
```json
"dungeons": {
  "v": {
    "_saved_dungeons": {
      "v": [],
      "type": 100
    },
    "_global_seed": {
      "v": 42763,
      "type": 3
    }
  },
  "type": 250
}
```
---
after unlocking the dungeon and entering level 1, `savedata.dungeons._saved_dungeons` is an array of 15 such objects:
```json
{
  "v": {
    "is_empty": {
      "v": true,
      "type": 1
    },
    "dungeon_preset_name": {
      "v": "",
      "type": 11
    },
    "seed": {
      "v": -1,
      "type": 3
    },
    "random_calls_count": {
      "v": 0,
      "type": 16
    },
    "objects": {
      "v": [],
      "type": 100
    },
    "is_completed": {
      "v": false,
      "type": 2
    }
  },
  "type": 250
},
```
the already visited level 1 (0th array index) instead has:
* `is_empty = false`
* `dungeon_preset_name = "1"`
* `objects` filled with the map data
* `seed = 19995` (note this is different from the global seed, i guess the global one is used to generate per-level ones so they can quickly be seeded to speed up level generation)
* `random_calls_count = 46148` (my guess is this is used to "skip" the rng forward from the seed when reloading the map, to prevent it from accidentally e.g. generating always the same loot)

there's also a `savedata.dungeon_seed` integer which equals the `savedata.dungeons._global_seed`, which would probably also need to be reset if one wants to reseed the dungeon layout.

---
so yeah it looks to me like resetting the dungeon is as easy as clearing `savedata.dungeons._saved_dungeons`, while also reseeding it would mean additionally setting `savedata.dungeon_seed` and `savedata.dungeons._global_seed` to the same new seed integer

**Comment by NetroScript** [comment]
I will take a look at it, and will most likely will implement it as you suggested
