### ISSUE TITLE
[BUG] Can't load .dat save file

### ISSUE THREAD

**Issue by IceLitty** [NetroScript/Graveyard-Keeper-Savefile-Editor#73]
**Describe the bug**
Can't load .dat save file
My exception isn't from decode.py, so I think this is not as same as #66 , but I have two DLCs and active them in editor
```batch
Looking for save files in the folder: C:\Users\IceLitty\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper
Beginning to decode file: C:\Users\IceLitty\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\1.dat
Extracting String Array
Extracting header
Extracting game objects
Loaded file: C:\Users\IceLitty\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\1.dat
Traceback (most recent call last):
  File "S:\Programme\Python3.5\lib\site-packages\gevent\greenlet.py", line 536, in run
  File "S:\Programme\Python3.5\lib\site-packages\eel\__init__.py", line 190, in _process_message
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 169, in get_savefile
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 742, in editable_values
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 799, in get_inventory
TypeError: unhashable type: 'dict'
Sun Jan 10 00:45:47 2021 <Greenlet at 0x21f311cb930: _process_message({'call': 1.7924956750958854, 'args': ['1', '336016, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with TypeError
```

**To Reproduce**
save file: [1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/5791474/1.zip)

**Expected behavior**
On load save from the main page.

**Screenshots**

**Please also add the following Information:**
Use windows version 0.1.22

**Additional context**

**Comment by NetroScript** [comment]
Hey, I found and fixed the problem.
Your specific use case is working now.

Although it is still possible that adding new items may cause invalid item ids when adding them (if they weren't in the save before) - but I think the chance for that is so low, that I currently don't see the need to add special cases for them.

You can try out if it works now with a hotfixed version of 0.1.22 - you can get it for windows [here](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/releases/download/0.1.22/Graveyard.Keeper.Savefile.Editor.-.Windows.-.0.1.22.Hotfix.zip).
