### ISSUE TITLE
[BUG] Replace Bodies in Grave have red skulls

### ISSUE THREAD

**Issue by WizzleWuzzle** [NetroScript/Graveyard-Keeper-Savefile-Editor#77]
When using the "Replace Bodies in Graves with a 26 Skull" option, all bodies get replaced with a 7 Red, 26 White body. The Heart/Brain/Intestines are all 3R3W. This makes the graves have a maximum rating of 19 instead of 26 due to the red skulls

**Comment by NetroScript** [comment]
You remind me of a small error I did, I used the same body which I used for the 26 skull workers, but forgot, that for the workers the red skulls don't matter.

I will fix it, but until I fixed it, you can use for example the value of 27 skulls, which will use my custom function, which will never have red skulls.

**Comment by NetroScript** [comment]
Can you now try it again?

You either have to download the same release again (if you want to replace everything) or you just need to replace the file `data.json` which you can find in the `data` folder. The up to date version of this file can be found [here](https://raw.githubusercontent.com/NetroScript/Graveyard-Keeper-Savefile-Editor/master/data/data.json).

**Comment by Kiwibomber** [comment]
With replaced data.json the issue is fixed. 
Thanks,
