### ISSUE TITLE
You've said we can message you to fix the save

### ISSUE THREAD

**Issue by IKnewOne** [NetroScript/Graveyard-Keeper-Savefile-Editor#8]
Can you fix the save i've sent you, or mine is corrupt?
Sorry for using issues, i'm not sure how to 'message' in github

**Comment by NetroScript** [comment]
You want me to fix the save file you uploaded earlier? Or a different one?

**Comment by NetroScript** [comment]
Sorry, my fault for not reading correctly, the attached file is the save you sent me before, fixed.
[repaired.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2332690/repaired.zip)
