### ISSUE TITLE
[BUG] Windows not working for me, suck at python.

### ISSUE THREAD

**Issue by ChaoticAndy** [NetroScript/Graveyard-Keeper-Savefile-Editor#90]
![20231209_210538](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/assets/153406006/b5d51cec-2536-4247-94d7-0f2f62723342)
![20231209_210452](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/assets/153406006/01e8eb87-5ba7-4570-ab6d-a3cf1bbb2d09)
![20231209_210437](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/assets/153406006/8661483e-3df1-4cec-aeae-a9c6f06414ec)

Using phone so might be bad lol

Bug is as seen just windows version anytime I open a save file it tells me that it's wrong or that it needs updating (latest version) 
Other is I suck at python and I'm trying to follow the directions lmao figured if windows isn't working go to python but can't get it to work because I'm not good at it.

To reproduce all I'm doing is opening any .Dat file gives me that response and nothing else. Tried windows version 0.1.24 and 0.1.23
To reproduce python end just I guess try to do things without knowing anything lmfao. Using latest version as well.

**Comment by NetroScript** [comment]
@ChaoticAndy 
Can you upload one of your save files (which is not working) so I can take a look at it? 

You can zip it in Windows, and then just drag and drop this file onto the text field on GitHub to upload it. 

Alternatively, you can use this button:

![image](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/assets/18115780/ff72eb18-8b99-446a-94c6-507c892292a7)

----------------------

Also, in theory when opening the `.exe` file, you should get a black window (the command line window) which s output at which step of parsing the program is failing. 

If there is no output, there is potentially also a problem in the communication between the browser window and the application itself. 

I will first check if I can open the `.dat` file locally on my machine -> If I also can't open it, I will figure out the issue causing it. If the file opens fine, it might be a problem with the communication with the browser on your PC, then I will instruct you on additional steps which help me in debugging it.

**Comment by ChaoticAndy** [comment]
[Dat files.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/13640815/Dat.files.zip)

Here is the files i've been trying and the only .dat files i've found in the folders. I have 2 files and want to edit the one because of the bug that makes you not get Clotho's items for the sin shard questline. Could it be because i'm using steam to play possibly? 

I assume you mean when opening the windows version so i quickly tried that before replying (as i'm getting nowhere fast with python lmao) when i try opening one of the dat files it says it starts the "traceback" after extracting the string array. After traceback it has a "struct.error: unpack requires a bytes object of length 4"
Hopefully you have more luck than I.

**Comment by NetroScript** [comment]
Are you sure you uploaded the correct files?

All of the files you uploaded have a size of either 512 Bytes or 128 Bytes.

In no way this is a file which can be loaded by Graveyard Keeper. 

As the entire game state is normally stored within the save files, they have a size of multiple MB when not zipped.  

Your files also contain text only (so symbols in the range of a-Z and 0-9).

**Comment by NetroScript** [comment]
Ah, seeing this reddit post: https://www.reddit.com/r/GraveyardKeeper/comments/18gn45y/is_there_is_something_wrong_with_the_size_of_the/

And checking with my own install, the files you sent are the data files which are used to confirm if the DLC is installed. 

On my PC this is for example here:

`S:\Steam\steamapps\common\Graveyard Keeper\Graveyard Keeper_Data`

The save files on the other hand, are located here:

`C:\Users\%username%\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper` 

(On Windows, but this may also differ)

Each .dat file should have a .info file with exactly the same name.

**Comment by ChaoticAndy** [comment]
Ah yes thank you! 
Still couldn't find it and had to literally copy/paste a line of it into the file path to get to it lmao.

Windows worked beautifully as soon as I got that sorted out thanks a ton. The save editor is also amazing good job on it 😊
